export const urlPrefix = 'https://api.huobi.pro'
export const baseCoin = 'usdt'
export const apiDomain = 'api.huobi.pro'
export const huobiwss = 'wss://api.huobi.pro/ws'
export const localProxy = 'http://127.0.0.1:10800'
