export const CUSTOMCONNSTR_cosmosstring = localStorage.getItem('CUSTOMCONNSTR_cosmosstring') ?? 'xxx'
export const huobi_read_access = localStorage.getItem('huobi_read_access') ?? 'xxx'
export const huobi_read_secret = localStorage.getItem('huobi_read_secret') ?? 'xxx'
export const huobi_trade_access = localStorage.getItem('huobi_trade_access') ?? 'xxx'
export const huobi_trade_secret = localStorage.getItem('huobi_trade_secret') ?? 'xxx'